# Build Stage
FROM node:18 as builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build frontend

# Serve Stage
FROM nginx:alpine
COPY --from=builder /app/dist/apps/frontend /usr/share/nginx/html

# Optional: Add custom nginx config
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
